### Example below is to showcase on what numpy can do other than using normal lists.

In [1]:
import numpy as np
a = np.array([1,2,3] dtype='int16')
b = np.array([4,5,6])

print(a*b)

[ 4 10 18]


### Here is an example with using lists only.

In [2]:
a = [1,3,5]
b = [4,5,6]
print(a*b)

TypeError: can't multiply sequence by non-int of type 'list'

^^ Above here will give u an error.

The Basics:

In [3]:
a = np.array([1,2,3], dtype='int16') # can declare the type here
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]]) # brackets are important here.
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get dimentions
print(a.ndim)
print(b.ndim)


1
2


In [11]:
# Get the shapes (rows and columns)
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [24]:
# Get type
print(a.dtype)
print(b.dtype)

int32
float64


In [23]:
# Get size
print(a.itemsize)
print(b.itemsize)

# total size
print(a.nbytes)
print(b.nbytes)

4
8
12
48
