## Mathematics


In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
a + 2


array([3, 4, 5, 6])

In [3]:
a - 2


array([-1,  0,  1,  2])

In [4]:
a * 2 


array([2, 4, 6, 8])

In [5]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [6]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [7]:
a ** 2

array([ 1,  4,  9, 16])

In [8]:
# Take sin of all values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear Algebra

In [14]:
a = np.ones((2,3), dtype='int32')
print(a)

print('')

b = np.full((3,2), 2)
print(b)

# To multiply a matrix
np.matmul(a,b)

[[1 1 1]
 [1 1 1]]

[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [19]:
# Find the determinant
c = np.identity(3, dtype='int32')
c

np.linalg.det(c)

1.0

##### Statistics


In [20]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.min(stats, axis=1)

array([1, 4])

In [26]:
np.max(stats, axis=1)

array([3, 6])

In [29]:
np.sum(stats, axis=1)

array([ 6, 15])