In [1]:
import numpy as np

##### Reorganizing Arrays

In [8]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
print('')


after = before.reshape((4,2))
print(after)
print('')

after2 = before.reshape((2,2,2))
print(after2)


[[1 2 3 4]
 [5 6 7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


##### Make sure that the parameters make sense.
Below is an error:

In [9]:
after = before.reshape((2,3))
print(after)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [11]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
# Horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))



print(h1)
print('')
print(h2)


np.hstack([h1,h2])





[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])